Increase `numViews` synchronously to avoid SQLite error
Error: SQLite3 returned ErrorBusy while attempting to perform close: unable to
       close due to unfinalized statements or unfinished backups.